### Assignment 5: A* Search for a Puzzle Solver

Objective: Solve the 8-puzzle using A* search.

Problem Statement: The 8-puzzle involves sliding tiles to achieve a goal state. Use A* to solve it.

#### Tasks:

Define heuristic functions:
* H1: Number of misplaced tiles.
* H2: Sum of Manhattan distances of all tiles from their goal positions.
* Implement A* with both heuristics.
* Compare the performance of the two heuristics in terms of the number of nodes
explored and solution depth.

In [ ]:
import heapq
import numpy as np

class PuzzleState:
    def __init__(self, board, parent=None, move=None, depth=0, cost=0):
        self.board = board
        self.parent = parent
        self.move = move
        self.depth = depth
        self.cost = cost
        self.blank_pos = self.find_blank()

    def find_blank(self):
        for i in range(3):
            for j in range(3):
                if self.board[i][j] == 0:
                    return (i, j)

    def get_neighbors(self):
        neighbors = []
        x, y = self.blank_pos
        moves = {"Up": (x-1, y), "Down": (x+1, y), "Left": (x, y-1), "Right": (x, y+1)}

        for move, (nx, ny) in moves.items():
            if 0 <= nx < 3 and 0 <= ny < 3:
                new_board = np.copy(self.board)
                new_board[x][y], new_board[nx][ny] = new_board[nx][ny], new_board[x][y]
                neighbors.append(PuzzleState(new_board, self, move, self.depth + 1))

        return neighbors

    def __lt__(self, other):
        return (self.cost, self.depth) < (other.cost, other.depth)

def heuristic_misplaced(state, goal):
    return np.sum(state.board != goal) - 1  # Subtract 1 for the blank tile

def heuristic_manhattan(state, goal):
    distance = 0
    for i in range(3):
        for j in range(3):
            if state.board[i][j] != 0:
                x, y = divmod(np.where(goal == state.board[i][j])[0][0] * 3 + np.where(goal == state.board[i][j])[1][0], 3)
                distance += abs(i - x) + abs(j - y)
    return distance

def astar(start, goal, heuristic):
    open_list = []
    closed_set = set()
    heapq.heappush(open_list, (0, start))
    nodes_explored = 0

    while open_list:
        _, current = heapq.heappop(open_list)
        nodes_explored += 1

        if np.array_equal(current.board, goal):
            return current, nodes_explored

        closed_set.add(tuple(map(tuple, current.board)))

        for neighbor in current.get_neighbors():
            if tuple(map(tuple, neighbor.board)) in closed_set:
                continue
            neighbor.cost = neighbor.depth + heuristic(neighbor, goal)
            heapq.heappush(open_list, (neighbor.cost, neighbor))

    return None, nodes_explored

def print_solution(state):
    path = []
    while state:
        path.append(state.board)
        state = state.parent
    for board in reversed(path):
        print(board, "\n")

start_board = np.array([[1, 2, 3], [4, 0, 5], [6, 7, 8]])
goal_board = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
start_state = PuzzleState(start_board)
print("Solving with Misplaced Tiles heuristic:")
solution, nodes1 = astar(start_state, goal_board, heuristic_misplaced)
print_solution(solution)
print(f"Nodes explored: {nodes1}\n")
print("Solving with Manhattan Distance heuristic:")
solution, nodes2 = astar(start_state, goal_board, heuristic_manhattan)
print_solution(solution)
print(f"Nodes explored: {nodes2}")

Solving with Misplaced Tiles heuristic:
[[1 2 3]
 [4 0 5]
 [6 7 8]] 

[[1 2 3]
 [4 5 0]
 [6 7 8]] 

[[1 2 3]
 [4 5 8]
 [6 7 0]] 

[[1 2 3]
 [4 5 8]
 [6 0 7]] 

[[1 2 3]
 [4 5 8]
 [0 6 7]] 

[[1 2 3]
 [0 5 8]
 [4 6 7]] 

[[1 2 3]
 [5 0 8]
 [4 6 7]] 

[[1 2 3]
 [5 6 8]
 [4 0 7]] 

[[1 2 3]
 [5 6 8]
 [4 7 0]] 

[[1 2 3]
 [5 6 0]
 [4 7 8]] 

[[1 2 3]
 [5 0 6]
 [4 7 8]] 

[[1 2 3]
 [0 5 6]
 [4 7 8]] 

[[1 2 3]
 [4 5 6]
 [0 7 8]] 

[[1 2 3]
 [4 5 6]
 [7 0 8]] 

[[1 2 3]
 [4 5 6]
 [7 8 0]] 

Nodes explored: 363

Solving with Manhattan Distance heuristic:
[[1 2 3]
 [4 0 5]
 [6 7 8]] 

[[1 2 3]
 [4 5 0]
 [6 7 8]] 

[[1 2 3]
 [4 5 8]
 [6 7 0]] 

[[1 2 3]
 [4 5 8]
 [6 0 7]] 

[[1 2 3]
 [4 5 8]
 [0 6 7]] 

[[1 2 3]
 [0 5 8]
 [4 6 7]] 

[[1 2 3]
 [5 0 8]
 [4 6 7]] 

[[1 2 3]
 [5 6 8]
 [4 0 7]] 

[[1 2 3]
 [5 6 8]
 [4 7 0]] 

[[1 2 3]
 [5 6 0]
 [4 7 8]] 

[[1 2 3]
 [5 0 6]
 [4 7 8]] 

[[1 2 3]
 [0 5 6]
 [4 7 8]] 

[[1 2 3]
 [4 5 6]
 [0 7 8]] 

[[1 2 3]
 [4 5 6]
 [7 0 8]] 

[[1 2 3]
 [4 5 6]
 [7 8 0]